### ISSUE TITLE
Mod can't be loaded correctly with 3.7.0.152 TiC.

### ISSUE THREAD

**Issue by Nekros39** [Minemobs/constructsarmory#4]
#### Versions:
* Construct's Armory: 1.18.2-alpha.2
* Tinkers' Construct: 1.18.2-3.7.0.152
* Mantle: 1.18.2-1.9.50
* Forge: 1.18.2-40.2.17
#### Observed Behavior: 
This mod can't be loaded correctly.
#### Expected Behavior:
Entering game normally.
#### Steps to Reproduce:
1. Launch game with this mod alpha2 ver and latest TiC.

Crash Log: 
https://hastebin.com/share/owikucuzaz.perl

**Comment by Nekros39** [comment]
It seems caused by migration of modifier related classes, e.g. the cultivated modifier.

**Comment by SkyanUltra** [comment]
> It seems caused by migration of modifier related classes, e.g. the cultivated modifier.

I'm having this exact issue myself on Tinkers' Construct: 1.18.2-3.7.1.155, even when disabling all other mods in my modpack and only leaving on Mantle, TiC, and this mod.

**Comment by Minemobs** [comment]
I'll look into it tomorrow

**Comment by Minemobs** [comment]
That's weird, I cannot reproduce this issue with the latest (non beta) versions of Tinkers' Construct and Mantle

**Comment by Minemobs** [comment]
So I was able to reproduce the crash, someone forked the mod to fix the issue https://github.com/TeamSussy/constructsarmory but it crashes when trying to access the Properties.tab function.
I'll make a fix, It should be out in less than 2 hours
