### ISSUE TITLE
Overslimed armour causes texture error

### ISSUE THREAD

**Issue by nintyuk** [Minemobs/constructsarmory#6]
#### Versions (Be specific, do not write "latest"):
* Construct's Armory: 2.0.0-alpha.21.18.2
* Tinkers' Construct: 1.18.2-3.6.4.113
* Mantle: 1.18.2-1.9.50
* Forge: 40.2.0
#### Steps to Reproduce: Apply Slime Balls to Crafted Armour in Tinkers Anvil

![Minecraft Screenshot 2024-05-04 182342](https://github.com/Minemobs/constructsarmory/assets/4965151/f0b860c7-feb9-4d37-9efe-1bc1a55e085c)
![Minecraft Screenshot 2024-05-04 182439](https://github.com/Minemobs/constructsarmory/assets/4965151/96091232-d09d-4818-98f3-a4cbc29bfbaf)

**Comment by Minemobs** [comment]
Will be fixed in the next release, it should come out in an hour
![image](https://github.com/Minemobs/constructsarmory/assets/38861340/15c2a055-1f4f-40b6-b0ab-4d5bc12038e8)
